name: dsan5400
channels:
  - apple
  - conda-forge
dependencies:
  - datasets
  - jupyterlab
  - more-itertools
  - nltk
  - numpy
  - pydantic
  - pytorch
  - pyyaml
  - pip
  - pytest
  - python
  - pickle
  - json
  - jupyter
  - tqdm
  - transformers
  - spacy
  - scipy
  - scikit-learn
  - pandas
  - matplotlib
  - bs4
  - openai==0.28.0
  - collections
  - csv
  - re
